# Generated by Django 5.0.4 on 2024-04-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='id',
        ),
        migrations.AddField(
            model_name='todo',
            name='my_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
